name: Publish to Edge Store

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip Extension
        run: |
          zip -r linkedin_extension.zip . -x "*.git*"

      - name: Upload to Edge Add-ons
        uses: wdzeng/edge-addon@v1
        with:
          product-id: ${{ secrets.PRODUCTID }}
          client-id: ${{ secrets.CLIENTID }}
          client-secret: ${{ secrets.APIKEY }}
          file: linkedin_extension.zip
